Regla del trapecio y Regla de Simpson
serlomudata/SIQ025-Integracion pull request #2
Opened 2021-07-13 18:55 UTC by serlomudata

Se quieren anadir las siguientes reglas al paquete: Regla del trapecio y Regla de Simpson

2021-07-14 20:39 UTC, aalcacer requested changes

2021-07-14 20:39 UTC, aalcacer commented on R/trapecio.R
> +#' regla_trapecio(2.5,3.14,function(x){return(cos(x))})
Añade un ejemplo más :)

2021-07-18 18:51 UTC, serlomudata commented on R/trapecio.R
> +#' regla_trapecio(2.5,3.14,function(x){return(cos(x))})
Cambios añadidos.

2021-07-26 16:22 UTC, aleixalcacer approved these changes

2021-07-26 16:22 UTC, aalcacer approved these changes

2021-07-28 11:44 UTC, merged